[project]
name = "ai-econ-daioe-months"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "path>=17.1.1",
    "pathlib>=1.0.1",
    "polars>=1.38.1",
]
